language: python
sudo: false
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
python:
  - 2.7
env:
  - PLONE_VERSION=4.1.x
  - PLONE_VERSION=4.2.x
  - PLONE_VERSION=4.3.x
  - PLONE_VERSION=4.3.x-LP
  - PLONE_VERSION=5.0.x
matrix:
  allow_failures:
    - env: PLONE_VERSION=5.0.x
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
  - virtualenv .
  - bin/pip install --upgrade pip setuptools zc.buildout coveralls
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - sed -ie "s#plone-4.3.x.cfg#plone-$PLONE_VERSION.cfg#" travis.cfg
  - bin/buildout -N -t 3 -c travis.cfg
script:
  - bin/code-analysis
  - bin/test --all
after_success:
  - bin/createcoverage
  - bin/python -m coverage.pickle2json
  - bin/coveralls
